#!/usr/bin/python

# Copyright (c) 2014, Gabriel Hjort Blindell <ghb@kth.se>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.



#=========
# IMPORTS
#=========

import json
import os.path
import sys



#================
# HELP FUNCTIONS
#================

def error(msg):
    sys.stderr.write("ERROR: " + msg + "\n")
    sys.exit(1)

def extractData(line):
    pos = line.find("=")
    if pos < 0:
        raise SyntaxError("Expected '=' not found")
    name = line[:pos].strip()
    data = toValue(line[pos + 1:].strip())
    return name, data

def toValue(s):
    s = s.strip()
    if len(s) == 0:
        raise SyntaxError("No data")
    if s[0] == '[':
        if not s[-1] == ']':
            raise SyntaxError("Expected ']' not found")
        values = []
        for t in s[1:-1].split(','):
            if len(t) == 0:
                continue
            values.append(toValue(t))
        return values
    else:
        if s == "true":
            return True
        elif s == "false":
            return False
        elif s.isdigit():
            return int(s)
        else:
            return s

def consistsOnlyOf(s, ch):
    for c in s:
        if c != ch:
            return False
    return True

def getDataByName(data, name):
    for d in data:
        if d[0] == name:
            return d[1]

def getRequiredDataByName(data, name):
    d = getDataByName(data, name)
    if d == None:
        error("Required data '" + name + "' not found")
    return d



#=============
# MAIN SCRIPT
#=============

# Check solution file
if len(sys.argv) < 2:
    sys.stderr.write("No solution file\n")
    sys.exit(1)
if len(sys.argv) > 2:
    sys.stderr.write("Too many arguments\n")
    sys.exit(1)
solution_file = sys.argv[1]
if not os.path.isfile(solution_file):
    error("Solution file '" + solution_file +"' not found")

# Read solution file
content = []
with open(solution_file, 'r') as file:
    content = file.readlines()

# Extract data
all_data = []
for i in range(len(content)):
    linenr = str(i + 1)
    line = content[i].strip()
    if len(line) == 0 or consistsOnlyOf(line, '-') or consistsOnlyOf(line, '='):
        continue
    try:
        name, data = extractData(line)
    except SyntaxError as e:
        error("Line " + linenr + ": " + str(e))
    if getDataByName(all_data, name) != None:
        error("Line " + linenr + ": Duplicate entries with name '" + name + "'")
    all_data.append([name, data])

# Add, modify, or remove certain data in order to facilitate postprocessing

# Remove the null label from bb-order
bb_order_data = getRequiredDataByName(all_data, "bb_order")
null_label = getRequiredDataByName(all_data, "null_label")
try:
    null_label = int(null_label)
except ValueError:
    error("Value of 'null_label' is not an int")
if null_label < 0 or null_label >= len(bb_order_data):
    error("Value of 'null_label' is out of bounds")
del bb_order_data[null_label]

# Add 'has_dnode_imm' array to data
dn_reg_data = getRequiredDataByName(all_data, "dn_reg")
reg_for_imm_values = getRequiredDataByName(all_data, "reg_for_imm_values")
has_dnode_imm_data = []
for reg in dn_reg_data:
    has_dnode_imm_data.append(reg == has_dnode_imm_data)
all_data.append(["has_dnode_imm", has_dnode_imm_data])

# Turn desirable data into JSON
data_table = [ ["dn_reg",             "reg-selected-for-dnode"]
             , ["dn_imm",             "imm-value-of-dnode"]
             , ["has_dnode_imm",      "has-dnode-imm-value"]
             , ["dn_def",             "dnode-defined-by-pi"]
             , ["sn_def",             "snode-defined-by-pi"]
             , ["pi_sel",             "is-pi-selected"]
             , ["pi_bb",              "bb-allocated-for-pi"]
             , ["bb_order",           "order-of-bbs"]
             ]
keep_table = [ d[0] for d in data_table ]
replace_table = [ d[1] for d in data_table ]
json_data = {}
for d in all_data:
    name = d[0]
    for i in range(len(keep_table)):
        if name == keep_table[i]:
            json_data[replace_table[i]] = d[1]
            del keep_table[i]
            del replace_table[i]
            break
if len(keep_table) > 0:
    error("Required data '" + keep_table[0] + "' not found")

# Print JSON
print json.dumps(json_data)
