#!/bin/bash

# Copyright (c) 2014, Gabriel Hjort Blindell <ghb@kth.se>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.



#==========
# SETTINGS
#==========

THIS_DIR=$(dirname $0)
JSON_INPUT_FILE=$1
MINIZINC_INPUT_FILE="$THIS_DIR/input.mzn"
MINIZINC_OUTPUT_FILE="$THIS_DIR/input.sol.mzn"
MINIZINC_MODEL_FILE="$THIS_DIR/model.mzn"
JSON_SOLUTION_FILE_SUFFIX="sol.json"
JSON_SOLUTION_FILE=""   # Will be set after parsing command-line arguments
POSTPROCESSING_INFO_FILE="$THIS_DIR/post-params.json"



#================
# HELP FUNCTIONS
#================

function checkStatus {
    if [ $? -ne 0 ]; then
        exit 1
    fi
}



#=============
# MAIN SCRIPT
#=============

# Check arguments
if [ -z "$1" ]; then
    echo "No JSON file provided"
    exit 1
fi

JSON_SOLUTION_FILE="$THIS_DIR/$(basename ${1%.*}.$JSON_SOLUTION_FILE_SUFFIX)"

# Generate input to Minizinc model
echo "Generating Minizinc input..."
$THIS_DIR/mzn-input-gen \
    --model-params-file="$MINIZINC_INPUT_FILE" \
    --postprocessing-params-file="$POSTPROCESSING_INFO_FILE" \
    $JSON_INPUT_FILE
checkStatus

# Run Minizinc solver
echo "Running Minizinc solver..."
CURRENT_DIR=`pwd`
cd $THIS_DIR
minizinc $(basename $MINIZINC_MODEL_FILE) > $(basename $MINIZINC_OUTPUT_FILE)
STATUS=$?
cd $CURRENT_DIR
if [ $STATUS -ne 0 ]; then
    exit 1
fi

# Convert solution into JSON format
echo "Converting Minizinc solution to JSON format..."
$THIS_DIR/mzn-solution-to-json $MINIZINC_OUTPUT_FILE > $JSON_SOLUTION_FILE
checkStatus
