#!/bin/bash

# Copyright (c) 2014, Gabriel Hjort Blindell <ghb@kth.se>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.



#================
# HELP FUNCTIONS
#================

function checkStatus {
    if [ $? -ne 0 ]; then
        exit 1
    fi
}

MINIZINC_INPUT_FILE="input.mzn"
MINIZINC_SOLUTION_FILE="input.sol.mzn"
JSON_SOLUTION_FILE_SUFFIX="sol.json"
JSON_SOLUTION_FILE=""   # Will be set after parsing command-line arguments



#=============
# MAIN SCRIPT
#=============

# Check arguments
if [ -z "$1" ]; then
    echo "No JSON file provided"
    exit 1
fi

JSON_SOLUTION_FILE="${1%.*}.$JSON_SOLUTION_FILE_SUFFIX"

# Generate input to Minizinc model
echo "Generating Minizinc input..."
./input-gen $1 > $MINIZINC_INPUT_FILE
checkStatus

# Run Minizinc solver
echo "Running Minizinc solver..."
minizinc model.mzn > $MINIZINC_SOLUTION_FILE
checkStatus

# Convert solution into JSON format
echo "Converting Minizinc solution to JSON format..."
./mzn-solution-to-json $MINIZINC_SOLUTION_FILE > $JSON_SOLUTION_FILE
checkStatus
