#!/usr/bin/python

#  Main authors:
#    Gabriel Hjort Blindell <ghb@kth.se>
#
#  Copyright (c) 2012-2017, Gabriel Hjort Blindell <ghb@kth.se>
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright notice,
#     this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright notice,
#     this list of conditions and the following disclaimer in the documentation
#     and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the names of its contributors
#     may be used to endorse or promote products derived from this software
#     without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY
#  DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
#  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
#  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
#  ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
#  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.



#=========
# IMPORTS
#=========

import fractions
import json
import math
import os.path
import sexparser
import sys



#================
# HELP FUNCTIONS
#================

def error(msg):
    sys.stderr.write("ERROR: " + msg + "\n")
    sys.exit(1)

def bumpArrOfSing(json):
    output = []
    for d in json:
        if d is None:
            output.append(d)
        else:
            output.append(d+1)
    return output

def bumpValue(v):
    return v + 1

def bumpArr(json):
    return [ x + 1 for x in json ]

def bumpArrOfArr(json):
    return [ bumpArr(x) for x in json ]

VT_PLAIN = 0
VT_ARRAY1D = 1
VT_ARRAY2D = 2
VT_SET = 3
VT_ARRAY = 4
VC_AS_IS = 0
VC_SET = 1
VC_SINGLETON = 2
def dumpParams(
    json,
    var_name,
    var_type = VT_PLAIN,
    var_range = "",
    var_conv = VC_AS_IS
):
    sys.stdout.write(var_name)
    sys.stdout.write(" = ")
    if var_type == VT_PLAIN:
        sys.stdout.write(convData(json, var_conv))
    elif var_type == VT_ARRAY:
        sys.stdout.write("[")
        lst = ", ".join([ convData(d, var_conv) for d in json ])
        sys.stdout.write(lst)
        sys.stdout.write("]")

    elif var_type == VT_ARRAY1D:
        sys.stdout.write("array1d(")
        sys.stdout.write(var_range)
        sys.stdout.write(", [")
        lst = ", ".join([ convData(d, var_conv) for d in json ])
        sys.stdout.write(lst)
        sys.stdout.write("])")
    elif var_type == VT_ARRAY2D:
        sys.stdout.write("[|")
        rows = []
        for d in json:
            rows.append(", ".join([ convData(e, var_conv) for e in d ]))
        s = ", |".join(rows)
        sys.stdout.write(s)
        sys.stdout.write("|]")
    elif var_type == VT_SET:
        sys.stdout.write("{")
        lst = ", ".join([ convData(d, var_conv) for d in json ])
        sys.stdout.write(lst)
        sys.stdout.write("}")
    else:
        error("unknown variable type")
    sys.stdout.write(";\n\n")

def convData(d, var_conv):
    if var_conv == VC_SET:
        if hasattr(d, "__iter__"):
            return "{" + ", ".join([ str(e) for e in d ]) + "}"
        else:
            return "{" + str(d) + "}"
    elif var_conv == VC_SINGLETON:
        if d is None:
            return "{}"
        else:
            return "{" + str(d) + "}"
    else:
        return str(d)

def parseSExpr(s):
    return sexparser.parse(s)

def removeMatch(json, m):
    json["num-matches"] = json["num-matches"] - 1
    del json["match-operations-covered"][m]
    del json["match-latencies"][m]
    del json["match-entry-blocks"][m]
    new_match_fall_through_params = []
    for t in json["match-fall-through-block"]:
        if t[0] != m:
            if t[0] > m:
                t[0] = t[0] - 1
            new_match_fall_through_params.append(t)
    json["match-fall-through-block"] = new_match_fall_through_params
    return json

def computeOpCoverageDict(json):
    D = {}
    for m in range(json["num-matches"]):
        key = getOpCoverageKey(json["match-operations-covered"][m])
        m_cost = json["match-latencies"][m]
        if key in D:
            best_m = D[key]
            best_cost = json["match-latencies"][best_m]
        else:
            best_cost = sys.maxint
        if m_cost < best_cost:
            D[key] = m
    return D

def getOpCoverageKey(os):
    key = ""
    os_str = map(str, os)
    return ",".join(os_str)


#=============
# MAIN SCRIPT
#=============

# Check arguments
if len(sys.argv) < 2:
    sys.stderr.write("No JSON file provided\n")
    sys.exit(1)
if len(sys.argv) > 2:
    error("Too many arguments\n")
json_file = sys.argv[1]
if not os.path.isfile(json_file):
    error("JSON file '" + json_file +"' not found")

# Read JSON file
json_data = []
with open(json_file, 'r') as file:
    json_data = json.load(file)

# Compute GCD of frequencies
fqs = json_data["fun-block-exec-freqs"]
scaled = []
g = fqs[0]
for x in fqs:
    g = fractions.gcd(g, x)
for x in fqs:
    scaled.append(x / g)

# Remove all copy operations, as they can always be covered using a null pattern
copy_ops = set()
for m in json_data["match-copy-instrs"]:
    copy_ops = copy_ops | set(json_data["match-operations-covered"][m])
for m in range(json_data["num-matches"]):
    new_ops_covered = []
    for p in json_data["match-operations-covered"][m]:
        if p not in copy_ops:
            new_ops_covered.append(p - len([ q for q in copy_ops if q < p ]))
    json_data["match-operations-covered"][m] = new_ops_covered
json_data["fun-num-operations"] = \
    json_data["fun-num-operations"] - len(copy_ops)

# Compute cover cost for operations
cover_costs = []
for o in range(json_data["fun-num-operations"]):
    bs = json_data["fun-op-placements"][o]
    min_freq = sys.maxint
    for b in bs:
        min_freq = min(min_freq, json_data["fun-block-exec-freqs"][b])
    cover_costs.append(min_freq / g)

# Produce 'match-fall-through-block' parameters
params = []
for m in range(json_data["num-matches"]):
    for c in json_data["match-constraints"][m]:
        l = parseSExpr(c)
        if ( len(l) == 2 and l[0] == "fall-through"
             and len(l[1]) == 2 and l[1][0] == "block-of-bnode"
             and len(l[1][1]) == 2 and l[1][1][0] == "ai"
           ):
            fall_b = int(l[1][1][1])
            params.append([m, fall_b])
json_data["match-fall-through-block"] = params

# Remove matches that are useless for this model
queue = range(json_data["num-matches"])
while len(queue) > 0:
    m = queue.pop(0)
    if len(json_data["match-operations-covered"][m]) == 0:
        json_data = removeMatch(json_data, m)
        queue = [n-1 for n in queue]

# Sort operation coverage information
for i in range(len(json_data["match-operations-covered"])):
    os = json_data["match-operations-covered"][i]
    json_data["match-operations-covered"][i] = sorted(os)

# Remove matches that cover the same operations at equal or greater cost (but
# does not enforce any fall-through).
D = computeOpCoverageDict(json_data)
dominated_ms = []
ms_with_fallthrough = \
    set([ t[0] for t in json_data["match-fall-through-block"] ])
for m in range(json_data["num-matches"]):
    if m in ms_with_fallthrough:
        continue
    key = getOpCoverageKey(json_data["match-operations-covered"][m])
    if D[key] != m:
        dominated_ms.append(m)
queue = dominated_ms
while len(queue) > 0:
    m = queue.pop(0)
    json_data = removeMatch(json_data, m)
    queue = [n-1 for n in queue]

# Dump parameters for 1-based solver
dumpParams( json_data["fun-num-operations"]
          , "numOperationsInFunction"
          )
dumpParams( json_data["fun-num-blocks"]
          , "numBlocksInFunction"
          )
dumpParams( json_data["num-matches"]
          , "numMatches"
          )
dumpParams( g
          , "execFrequencyGCD"
          )
dumpParams( cover_costs
          , "coverCostOfOperationInFunction"
          , VT_ARRAY1D
          , "allOperationsInFunction"
          )
dumpParams( bumpArrOfArr(json_data["match-operations-covered"])
          , "operationsCoveredByMatch"
          , VT_ARRAY1D
          , "allMatches"
          , VC_SET
          )
dumpParams( bumpArrOfSing(json_data["match-entry-blocks"])
          , "entryBlockOfMatch"
          , VT_ARRAY1D
          , "allMatches"
          , VC_SINGLETON
          )
dumpParams( bumpArrOfArr(json_data["match-fall-through-block"])
          , "fallThroughBlockOfMatch"
          , VT_ARRAY2D
          )
dumpParams( json_data["match-latencies"]
          , "latencyOfMatch"
          , VT_ARRAY1D
          , "allMatches"
          )
