{-|
Copyright   :  Copyright (c) 2012-2016, Gabriel Hjort Blindell <ghb@kth.se>
License     :  BSD3 (see the LICENSE file)
Maintainer  :  ghb@kth.se
-}
{-
Main authors:
  Gabriel Hjort Blindell <ghb@kth.se>

-}

module Language.InstrSel.TargetMachines.Generators.HaskellCodeGenerator where

import Language.InstrSel.TargetMachines.Base
  ( TargetMachine (tmID)
  , fromTargetMachineID
  )
import Language.InstrSel.Utils
  ( replace )

import Language.Haskell.Exts



-------------
-- Functions
-------------

-- | Takes a 'TargetMachine' and generates corresponding Haskell source code.
-- The source code is then wrapped inside a module with name equal to the
-- 'Language.InstrSel.TargetMachines.IDs.TargetMachineID'.
generateModule :: TargetMachine -> String
generateModule tm =
  let renameFuncs str = replace "mkGraph" "I.mkGraph" str
      tm_id = fromTargetMachineID (tmID tm)
      boiler_src = "-----------------------------------------------------------\
                   \---------------------\n\
                   \-- |\n\
                   \-- Module      : UniIS.Targets." ++ tm_id ++ "\n\
                   \-- Stability   : experimental\n\
                   \-- Portability : portable\n\
                   \--\n\
                   \-- THIS MODULE HAS BEEN AUTOGENERATED!\n\
                   \--\n\
                   \-----------------------------------------------------------\
                   \---------------------\n\n"
      header_src = "module UniIS.Targets." ++ tm_id ++ "\n\
                   \  ( theTM )\n\
                   \where\n\n\
                   \import Language.InstrSel.Constraints\n\
                   \import Language.InstrSel.DataTypes\n\
                   \import Language.InstrSel.Graphs\n\
                   \import Language.InstrSel.Functions.IDs\n\
                   \import qualified Data.Graph.Inductive as I\n\
                   \import Language.InstrSel.OpStructures\n\
                   \import Language.InstrSel.OpTypes\n\
                   \import Language.InstrSel.TargetMachines\n\
                   \import Language.InstrSel.Utils\n\
                   \import Prelude \n\
                   \  hiding\n\
                   \  ( LT, GT )\n\
                   \import Data.Map\n\
                   \  ( fromList )\n\n"
      tm_func_src = "theTM :: TargetMachine\n\
                    \theTM = " ++ (renameFuncs $ show tm)
      haskell_code = header_src ++ tm_func_src
      res = parseFileContents haskell_code
      prettify m = prettyPrintStyleMode (style { lineLength = 80 })
                                        defaultMode m
  in case res
     of (ParseOk m) -> boiler_src ++ prettify m
        (ParseFailed line msg) -> error $ "generateModule: parsing failed at "
                                         ++ show line ++ ": " ++ msg
