#!/usr/bin/python

# Copyright (c) 2014, Gabriel Hjort Blindell <ghb@kth.se>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.



#=========
# IMPORTS
#=========

import argparse
import json
import os.path
import sys



#================
# HELP FUNCTIONS
#================

def error(msg):
    sys.stderr.write("ERROR: " + msg + "\n")
    sys.exit(1)

def createArgParser():
    parser = argparse.ArgumentParser()
    parser.add_argument("-spf", "--solution-params-file",
                        help="The JSON file containing the solution",
                        nargs=1,
                        required=True,
                        dest="SP_FILE")
    parser.add_argument("-ppf", "--post-params-file",
                        help="The JSON file containing the postprocessing " \
                            "parameters",
                        nargs=1,
                        required=True,
                        dest="PP_FILE")
    return parser



#=============
# MAIN SCRIPT
#=============

# Parse and check command-line arguments
parser = createArgParser()
args = parser.parse_args()
solution_file = args.SP_FILE[0]
if not os.path.isfile(solution_file):
    error("Solution file '" + solution_file +"' not found")
postparams_file = args.PP_FILE[0]
if not os.path.isfile(postparams_file):
    error("Postprocessing parameter file '" + postparams_file +"' not found")

# Parse JSON content
with open(solution_file, 'r') as fh:
    sol_data = json.load(fh)
with open(postparams_file, 'r') as fh:
    pp_data = json.load(fh)

# TODO: implement the rest
